all: pipe-Senzalettore pipe-Senzascrittore shellpipe 5Giu15-SoloFigli
pipe-Senzalettore: pipe-Senzalettore.c
	gcc -Wall -o pipe-Senzalettore pipe-Senzalettore.c
pipe-Senzascrittore: pipe-Senzascrittore.c
	gcc -Wall -o pipe-Senzascrittore pipe-Senzascrittore.c
shellpipe: shellpipe.c
	gcc -Wall -o shellpipe shellpipe.c
5Giu15-SoloFigli: 5Giu15-SoloFigli.c
	gcc -Wall -o 5Giu15-SoloFigli 5Giu15-SoloFigli.c