all: provaPipe-bis pipe-SenzaClose pipe-Generico1 pipe-Generico2 provaEsame1
provaPipe-bis: provaPipe-bis.c
	gcc -Wall -o provaPipe-bis provaPipe-bis.c
pipe-SenzaClose: pipe-SenzaClose.c
	gcc -Wall -o pipe-SenzaClose pipe-SenzaClose.c
pipe-Generico1: pipe-Generico1.c
	gcc -Wall -o pipe-Generico1 pipe-Generico1.c
pipe-Generico2: pipe-Generico2.c
	gcc -Wall -o pipe-Generico2 pipe-Generico2.c
provaEsame1: provaEsame1.c
	gcc -Wall -o provaEsame1 provaEsame1.c
