all: illegal pauseala pausekill pausekillWrong psignal loop
illegal: illegal.c
	gcc -Wall -o illegal illegal.c
pauseala: pauseala.c
	gcc -Wall -o pauseala pauseala.c
pausekill: pausekill.c
	gcc -Wall -o pausekill pausekill.c
pausekillwrong: pausekillWrong.c
	gcc -Wall -o pausekillWrong pausekillWrong.c
psignal: psignal.c
	gcc -Wall -o psignal psignal.c
loop: loop.c
	gcc -Wall -o loop loop.c