all: lungpipeConSegnali pipe-SenzalettoreConHandler
lungpipeConSegnali: lungpipeConSegnali.c
	gcc -Wall -o lungpipeConSegnali lungpipeConSegnali.c
pipe-SenzalettoreConHandler: pipe-SenzalettoreConHandler.c
	gcc -Wall -o pipe-SenzalettoreConHandler pipe-SenzalettoreConHandler.c