provaWait:
	gcc -Wall -std=c11 -o provaWait provaWait.c

unoDue:
	gcc -Wall -std=c11 -o unoDue unoDue.c

unoEdue:
	gcc -Wall -std=c11 -o unoEdue unoEdue.c

unoDueConPID-UID-GID:
	gcc -Wall -std=c11 -o unoDueConPID-UID-GID unoDueConPID-UID-GID.c

status1:
	gcc -Wall -std=c11 -o status1 status1.c

status2:
	gcc -Wall -std=c11 -o status2 status2.c


